apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mediawiki.persistence.size }}

