apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-credentials
type: Opaque
data:
  host: {{ .Values.mysql.host | b64enc | quote }}
  database: {{ .Values.mysql.database | b64enc | quote }}
  username: {{ .Values.mysql.username | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
  rootPassword: {{ .Values.mysql.rootPassword | b64enc | quote }}
